### PR TITLE
Add basic image rendering

### PR DESCRIPTION
**Pull request by Noskcaj19**
Blocking on weechat 2.6 (for more color pairs), a way to load the images async (hdata lines), and some config options.

### CODE REVIEW

**Comment by skuzzymiglet** [comment]
Is this PR going to be merged any time soon?

**Comment by Noskcaj19** [comment]
I'm not sure.  I figure this would probably be better served as a plugin.
Although, I believe the main blocker for this was Weechat not supporting enough color pair, which has been fixed.

**Comment by Noskcaj19** [comment]
Recent internal changes to buffers and messages actually make this fairly simple, I will try and get this merged soon.

**Comment by Noskcaj19** [comment]
Implement in 965737e (mk3)

**Pull request closed without merging**
